RECIPES = [
{
 "slug":"lamb-tagine","title":"Lamb Tagine","serves":"Serves 6",
 "blurb":"Slow-braised with apricots and warm spice, finished with cinnamon-toasted almonds.",
 "ing":[
  ("3 lb","1360 g","bone-in lamb stew meat or neck, cut into 1½-inch pieces"),
  ("2½ tsp","7 g","kosher salt, divided, plus more to taste"),
  ("1¾ cups","420 ml","lamb or chicken stock"),
  ("5 oz","142 g","dried apricots"),
  ("2 tbsp","27 g","extra-virgin olive oil, plus more as needed"),
  ("2 large","500 g","onions, thinly sliced"),
  ("1 tsp","6 g","tomato paste"),
  ("½ tsp","2 g","grated fresh ginger"),
  ("2 small","4 g","cinnamon sticks, used separately"),
  ("Large pinch","0.2 g","saffron"),
  ("½ tsp","1 g","ground ginger"),
  ("¾ tsp","2 g","ground turmeric"),
  ("¾ tsp","2 g","ground black pepper"),
  ("¼ tsp","0.6 g","ground cinnamon"),
  ("Pinch","0.2 g","freshly grated nutmeg"),
  ("⅓ cup","5 g","chopped fresh cilantro, divided"),
  ("1 tbsp","14 g","unsalted butter"),
  ("½ cup","54 g","slivered almonds"),
  ("2","30 g","scallions, finely chopped"),
  ("2 tbsp","8 g","chopped parsley"),
  ("","","Fresh lemon juice, to taste"),
 ],
 "steps":[
  "Toss the lamb with 2 tsp (5.6 g) of the salt in a large bowl. Hold at room temperature for an hour, or refrigerate up to a day.",
  "Bring the stock to a boil in a small pot, pull it off the heat, drop in the apricots, and leave them to soften for at least 15 minutes.",
  "Heat the oven to 325&deg;F (165&deg;C). Warm the oil over medium heat in a tagine, Dutch oven, or heavy pot with a tight lid. Brown the lamb in batches with space around each piece, roughly 10 minutes per batch, moving finished pieces to a plate.",
  "Pour off the rendered fat, leaving a thin film in the pot. Add the onions and &frac14; tsp (0.7 g) salt and cook until soft, about 8 minutes. Stir in the tomato paste, fresh ginger, one cinnamon stick, saffron, ground ginger, turmeric, pepper, ground cinnamon, and nutmeg, and cook until aromatic, about 2 minutes. Return the lamb with its juices, then add the apricots, stock, and half the cilantro. Seal with foil and the lid (foil is unnecessary in a tagine) and cook in the oven 2&frac12; to 3 hours, turning the meat now and then, until tender. Correct the seasoning.",
  "While it cooks, melt the butter with the second cinnamon stick in a small skillet over medium heat. Add the almonds and &frac14; tsp (0.7 g) salt and toast to golden brown, 5 to 7 minutes. Remove the cinnamon stick.",
  "Transfer the lamb and its juices to a platter. Scatter over the almonds along with the skillet butter, then the scallions, parsley, and remaining cilantro. Finish with lemon juice. Serve with flatbread or couscous.",
 ],
 "macros":[("Energy","520 kcal"),("Protein","30 g"),("Fat","33 g"),
           ("Carbohydrate","25 g (fiber 3 g)"),("Sodium","550 mg")],
 "note":"Per serving, estimated. The largest source of error is the bone-to-meat ratio, assumed at 65 percent edible yield, and how aggressively you drain the rendered fat. Sodium assumes Diamond Crystal and unsalted stock.",
},
{
 "slug":"marinara","title":"Marinara Sauce","serves":"Makes about 12 cups (2.8 L), 12 servings",
 "blurb":"Sweet onion and whole tomatoes, simmered down an hour and blended smooth.",
 "ing":[
  ("½ cup","108 g","extra-virgin olive oil"),
  ("2","500 g","Vidalia or other sweet onions, very coarsely chopped"),
  ("6 cloves","18 g","garlic, peeled"),
  ("2 tsp","2 g","dried oregano"),
  ("4 cans (28 oz)","3175 g","whole peeled tomatoes, with juices"),
  ("4 tsp","11 g","kosher salt, plus more to taste"),
  ("1½ tsp","3 g","freshly ground black pepper, plus more to taste"),
 ],
 "steps":[
  "Heat the oil in a large pot or Dutch oven over medium. Cook the onion and garlic, stirring now and then and keeping them from browning, until aromatic, about 3 minutes. Stir in the oregano.",
  "Crush the tomatoes by hand and add them to the pot with all their juices. Season with the salt and pepper.",
  "Bring to a boil, then drop to a gentle simmer. Cook uncovered, stirring occasionally, until slightly reduced, about 1 hour.",
  "Off the heat, blend smooth with an immersion blender. Correct the seasoning.",
 ],
 "macros":[("Energy","130 kcal"),("Protein","2 g"),("Fat","9 g"),
           ("Carbohydrate","10 g (fiber 3 g)"),("Sodium","800 mg")],
 "note":"Per 1-cup serving, estimated. Diamond Crystal assumed. Canned tomato sodium varies widely between brands; unsalted tomatoes drop it to roughly 380 mg. Keeps 5 days airtight in the refrigerator, or 6 months frozen. The garlic goes in whole and gets blended at the end; crush it first if you want it sharper.",
},
{
 "slug":"coq-au-vin","title":"Coq au Vin","serves":"Serves 5",
 "blurb":"Chicken legs braised in red wine with bacon and wild mushrooms.",
 "ing":[
  ("2 tbsp","27 g","vegetable oil, divided"),
  ("5","1700 g","skin-on, bone-in chicken legs"),
  ("","","Kosher salt and freshly ground black pepper"),
  ("12 oz","340 g","thick-cut bacon, cut crosswise into ⅓-inch slices"),
  ("3","180 g","carrots, peeled and chopped"),
  ("3 stalks","120 g","celery, minced"),
  ("1","170 g","onion, minced"),
  ("4 cups","960 ml","dry red wine such as Burgundy, divided"),
  ("½ cup","135 g","tomato paste"),
  ("1 qt","960 ml","low-sodium chicken broth"),
  ("12 sprigs","12 g","thyme"),
  ("6 sprigs","12 g","rosemary"),
  ("1 lb","454 g","assorted wild mushrooms, cut into bite-size pieces"),
 ],
 "steps":[
  "Heat the oven to 350&deg;F (175&deg;C). Warm 1 tbsp (13 g) of the oil in an ovenproof pot over medium-high heat. Season the chicken with salt and pepper and brown it in batches, 5 to 6 minutes per side. Move it to a plate.",
  "Add the bacon to the pot and cook until the fat renders. Add the carrots, celery, and onion and cook until the onion turns translucent, 7 to 8 minutes. Stir in 1 cup (240 ml) of the wine along with the tomato paste and simmer 2 to 3 minutes. Add the remaining 3 cups (720 ml) wine and boil until reduced by half, 15 to 20 minutes. Return the chicken to the pot.",
  "Add the broth. Tie the thyme and rosemary into a bundle and add it. Bring to a boil, cover, and braise in the oven until the chicken is tender, about 1&frac14; hours.",
  "Meanwhile, heat the remaining 1 tbsp (13 g) oil in a large pot over medium-high heat. Saut&eacute; the mushrooms until browned, about 5 minutes.",
  "Pull the herb bundle out and discard it, or the reduction will push the rosemary past pleasant. Lift the chicken into the pot with the mushrooms to keep warm. Simmer the sauce over medium heat until reduced by a third, about 20 minutes. Season with salt and pepper.",
  "Return the mushrooms and chicken to the sauce.",
 ],
 "macros":[("Energy","890 kcal"),("Protein","55 g"),("Fat","58 g"),
           ("Carbohydrate","20 g (fiber 4 g)"),("Sodium","1350 mg")],
 "note":"Per serving, estimated. Fat is the least stable figure, since it depends on whether you pour off rendered bacon fat; this assumes it all stays in. Sodium is driven by the bacon and moves with brand. Keeps 3 days: chill uncovered until cold, then cover, and rewarm before serving.",
},
{
 "slug":"oven-risotto","title":"Oven Risotto with Crispy Mushrooms","serves":"Serves 4",
 "blurb":"Baked rather than stirred, topped with mushrooms roasted until they crisp.",
 "ing":[
  ("1 lb","454 g","mixed wild, shiitake, or crimini mushrooms, sliced ¼ inch thick"),
  ("3 cloves","9 g","garlic, thinly sliced"),
  ("6 sprigs","6 g","thyme"),
  ("¼ tsp","0.5 g","crushed red pepper flakes"),
  ("¼ cup + 2 tbsp","81 g","extra-virgin olive oil, divided, plus more for drizzling"),
  ("1¾ tsp","5 g","kosher salt, divided"),
  ("1 medium","170 g","onion, finely chopped"),
  ("1 cup","200 g","arborio rice"),
  ("½ tsp","1 g","freshly ground black pepper"),
  ("½ cup","120 ml","dry vermouth or white wine"),
  ("3 cups","720 ml","chicken stock or low-sodium broth, divided"),
  ("2 oz","57 g","finely grated Parmesan"),
  ("2 tbsp","28 g","cold unsalted butter, cut into pieces"),
  ("½ tsp","1 g","finely grated lemon zest"),
  ("⅓ cup","10 g","coarsely chopped parsley"),
  ("","","Lemon wedges, for serving"),
 ],
 "steps":[
  "Set racks in the bottom third and middle of the oven and heat to 350&deg;F (175&deg;C). On a rimmed baking sheet, toss the mushrooms with the garlic, thyme, red pepper flakes, &frac14; cup (54 g) of the oil, and &frac12; tsp (1.4 g) of the salt. Roast on the bottom rack, tossing once halfway, until deeply golden and crisp, 25 to 30 minutes.",
  "Meanwhile, heat the remaining 2 tbsp (27 g) oil in a large ovenproof Dutch oven over medium-high. Cook the onion, stirring often, until softened, 3 to 5 minutes. Stir in the rice and season with the black pepper and &frac12; tsp (1.4 g) salt. Cook until some grains turn translucent, about 2 minutes. Add the vermouth, bring to a simmer, and cook until the pan is nearly dry, about 2 minutes. Add 2&frac12; cups (600 ml) of the stock, bring to a simmer, then cover and bake on the middle rack until the liquid is mostly absorbed and the rice is still slightly firm at the center, 16 to 18 minutes.",
  "Return the pot to the stove over medium heat. Add the remaining &frac12; cup (120 ml) stock and cook, stirring constantly, until the rice is tender with some bite and the sauce is creamy, about 2 minutes. Off the heat, stir in the Parmesan, butter, and lemon zest, and season with the remaining salt to taste. Loosen with a little warm water if needed; it should be thick but pourable.",
  "Turn out onto a platter, top with the crispy mushrooms and parsley, drizzle with oil, and serve with lemon wedges.",
 ],
 "macros":[("Energy","610 kcal"),("Protein","15 g"),("Fat","36 g"),
           ("Carbohydrate","52 g (fiber 4 g)"),("Sodium","1000 mg")],
 "note":"Per serving, estimated. Diamond Crystal assumed. Fat is high because the full quarter cup of roasting oil is counted, though some stays on the sheet. The mushrooms finish before the rice; leave them on the sheet rather than covering them, or you undo the crisping.",
},
{
 "slug":"herb-crusted-rack-of-lamb","title":"Herb-Crusted Rack of Lamb","serves":"Serves 4",
 "blurb":"Seared, crusted with garlic and soft herbs, roasted to medium-rare.",
 "ing":[
  ("2 racks","1360 g","frenched lamb, 8 ribs each, trimmed to a thin fat cap"),
  ("2 tsp","5.6 g","kosher salt, divided"),
  ("1¼ tsp","2.5 g","freshly ground black pepper, divided"),
  ("1 tsp","4 g","vegetable oil"),
  ("3 large cloves","12 g","garlic, minced"),
  ("¼ cup","15 g","finely chopped fresh parsley"),
  ("1 tbsp","3 g","finely chopped fresh thyme"),
  ("2 tsp","2 g","finely chopped fresh rosemary"),
  ("1½ tbsp","20 g","extra-virgin olive oil"),
 ],
 "steps":[
  "Heat a 12-inch heavy skillet over high heat until hot, at least 2 minutes.",
  "Pat the racks dry and rub them all over with 1&frac12; tsp (4.2 g) of the salt and &frac34; tsp (1.5 g) of the pepper. Add the vegetable oil to the skillet and sear the racks, in two batches if needed, until browned on all sides but not the ends, about 10 minutes per batch. Move them to a small roasting pan.",
  "Set a rack in the middle of the oven and heat to 350&deg;F (175&deg;C).",
  "Stir together the garlic, parsley, thyme, rosemary, olive oil, and the remaining &frac12; tsp (1.4 g) salt and &frac12; tsp (1 g) pepper. Coat the meaty side of each rack with the herb mixture, pressing it on. Roast 15 to 25 minutes, until a thermometer inserted diagonally into the center reads 125&deg;F (52&deg;C). Tent loosely with foil after 15 minutes so the frenched bones do not burn.",
  "Rest, covered, 10 minutes; the temperature will carry to 130&deg;F (54&deg;C) for medium-rare. Cut each rack into 4 double chops.",
 ],
 "macros":[("Energy","620 kcal"),("Protein","45 g"),("Fat","48 g"),
           ("Carbohydrate","1 g"),("Sodium","700 mg")],
 "note":"Per serving of two double chops, estimated. The dominant variable is how thin the fat cap is trimmed, which can swing the fat figure by 15 g per serving either way; bone weight is excluded. The rub goes on before the sear, so a good deal of that salt ends up in the pan. Salt the racks an hour ahead and pat them dry before searing if you want the seasoning to land more predictably.",
},
{
 "slug":"braised-chicken-olives-harissa","title":"Braised Chicken with Olives and Harissa","serves":"Serves 6",
 "blurb":"Thighs marinated in harissa and ras el hanout, braised over onions and tomato.",
 "ing":[
  ("2 tbsp","27 g","extra-virgin olive oil"),
  ("2 medium","340 g","yellow onions, thinly sliced"),
  ("3 medium","370 g","tomatoes, cored and cut into thin wedges"),
  ("3 to 3½ lb","1470 g","skin-on, bone-in chicken thighs"),
  ("¾ cup","180 g","mild harissa"),
  ("1 tsp","2 g","ras el hanout"),
  ("2 tsp","5.6 g","kosher salt, plus more for seasoning"),
  ("1 cup","140 g","green olives such as Castelvetrano, pitted and roughly chopped, divided"),
  ("8 cloves","24 g","garlic, peeled"),
  ("½ bunch","20 g","fresh cilantro, finely chopped"),
  ("¼ cup","60 ml","water"),
 ],
 "steps":[
  "Drizzle the oil into a large skillet with a tight-fitting lid and scatter the onions over it in an even layer. Lay the tomato wedges on top. Set aside.",
  "In a large bowl, toss the chicken thoroughly with the harissa, ras el hanout, and salt. Arrange the chicken and any remaining marinade in a single layer over the vegetables. Scatter half the olives, the garlic cloves, and the cilantro over the chicken, then pour in the water and cover.",
  "Set over high heat and cook just until the liquid simmers. Lower the heat to hold a simmer and cook, covered, until the chicken pulls apart easily with a fork, about 1&frac12; hours.",
  "If much liquid remains, uncover, leave the chicken in the pan, and raise the heat to high. Cook until the sauce thickens, swirling the pan occasionally so it does not scorch, 10 to 15 minutes.",
  "Off the heat, stir in the remaining olives. Serve with rice, mashed potatoes, or crusty bread.",
 ],
 "macros":[("Energy","560 kcal"),("Protein","38 g"),("Fat","40 g"),
           ("Carbohydrate","12 g (fiber 3 g)"),("Sodium","1250 mg")],
 "note":"Per serving, estimated, based on 3&frac14; lb of thighs with the skin left on. Sodium is dominated by the harissa and olives, both of which vary sharply by brand, so treat that figure as the softest here. Rendered chicken fat is counted in the sauce rather than discarded.",
},
]
